#cloud-config
#More details on the wifi setup here: https://gitlab.com/Bjorn_Samuelsson/raspberry-pi-cloud-init-wifi

# Enable password authentication with the SSH daemon
ssh_pwauth: true
hostname: $HOST_NAME

# On first boot, set the (default) ubuntu user's password to "ubuntu" and
# expire user passwords
chpasswd:
  expire: true
  list:
# root user name and password good idea to change
# TODO: Replace with rsa key
  - ubuntu:ubuntu

write_files:
- content: |
      network:
        version: 2
        wifis:
          wlan0:
            dhcp4: true
            access-points:
              "$WIFI_SSID":
                password: "$WIFI_PASSWORD"
  path: /etc/netplan/config.yaml

bootcmd:
  - 'systemctl disable systemd-networkd-wait-online.service'
  - 'systemctl mask systemd-networkd-wait-online.service'

runcmd:
  - 'rm /etc/netplan/??-cloud-init.yaml'
  - 'chmod go-r /etc/netplan/config.yaml'
  - 'netplan apply'
#wait for connection to network
  - /boot/firmware/waitForNetwork.sh
#update the time
  - sudo systemctl start systemd-timesyncd.service
  - sudo timedatectl set-ntp true
  - sudo systemctl restart systemd-timesyncd.service